### ISSUE TITLE
Download Link broken in README

### ISSUE THREAD

**Issue by maebert** [pkamenarsky/atea#12]
Should be updated to

```
https://github.com/downloads/pkamenarsky/atea/atea-1.0.1.dmg
```

(increase version by one...)

**Comment by pkamenarsky** [comment]
Can you tell me where exactly is the broken link? I thought I updated all of them today.

**Comment by maebert** [comment]
Oh, seems fixed, for some reason GitHub displayed an old version on the project's main page. Strange, but works now.
