### ISSUE TITLE
Menu items not clickable

### ISSUE THREAD

**Issue by macarthy** [pkamenarsky/atea#18]
For some reason I can't click the menu items. Even the Quit Atea item doesn't work.

I'm on 

OsX 10.6.8

with 

java version "1.6.0_29"
Java(TM) SE Runtime Environment (build 1.6.0_29-b11-402-10M3527)
Java HotSpot(TM) 64-Bit Server VM (build 20.4-b02-402, mixed mode)

Any ideas?

**Comment by macarthy** [comment]
I should clarify, the menu does close but the timer doesn't start; or in the case of the Quit Atea item, the app does not quit.

Using the dmg version 1.0.1

Thanks

**Comment by pkamenarsky** [comment]
We have identical systems. What's in your cfg file (~/.atea)?

**Comment by macarthy** [comment]
Just this 

{:file "/Users/macarthy/tasks.txt"}

**Comment by macarthy** [comment]
Figured out something , I had a tasks-times.csv, which I deleted and now I can click the items.

I think the issue is I had no tasks file when I started the app. But it still create the times file. when I later created the task file I the items are not clickable. 

Going to learn some closure in a few weeks, I'll dig into the code then :-)

**Comment by ecarter** [comment]
Had the exact same issue, same setup. Ended up deleting the default tasks.txt & tasks-times.csv and added the tasks.sh bash script to my bin path, opting not to have the default file but rely on a `tasks` alias to switch between task files.

The ability to quickly switch tasks files in terminal + native app is a win. Love the simplicity, can easily see this becoming something I rely on daily.

**Comment by pkamenarsky** [comment]
@macarthy Ah! That helps - I had something similar happen to me but thought I fixed it. I'll take a look.

For now a quick fix would be to delete the csv file, add something to the task file and then start up atea - then it should work normally.

**Comment by pkamenarsky** [comment]
https://github.com/downloads/pkamenarsky/atea/atea-1.0.3.dmg

**Comment by pkamenarsky** [comment]
Please close if fixed.

**Comment by ecarter** [comment]
1.0.3 is working as expected for me. Will let @macarthy do the honors since he opened it.
