### ISSUE TITLE
taskpaper

### ISSUE THREAD

**Issue by cj** [pkamenarsky/atea#23]
Hi,

Thank you for this!  I might start a branch to integrate this with [taskpaper](https://github.com/davidoc/taskpaper.vim) which will give syntax highlighting and a bunch of built in commands for atea :)

I think all that would be needed would be to update the way it parses the file.

**Comment by cj** [comment]
Here's what the taskpaper syntax looks like:

![](https://dl.dropbox.com/u/71697/jing/2012-02-22_0845.png)

**Comment by pkamenarsky** [comment]
Hey, glad you like it!

I guess it wouldn't be too hard, but before branching you might wanna take a look at this: https://github.com/pkamenarsky/atea/issues/11

**Comment by cj** [comment]
@pkamenarsky Thank you, I'm closing this as #11 would solve it :)
