### ISSUE TITLE
Support todo txt format

### ISSUE THREAD

**Issue by macarthy** [pkamenarsky/atea#7]
Cool app,

Maybe you should support the ToDo txt format, so you can use the Android and iPhone apps.
Details  https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format

Should support everything you need.

**Comment by pkamenarsky** [comment]
There's been some talk about configurable todo syntax support here: https://github.com/pkamenarsky/atea/issues/11
